name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          output: dist/snake.svg
      - name: Commit and push the snake animation
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add dist/snake.svg
          git commit -m "Generated snake animation"
          git push
